### ISSUE TITLE
check change to isValidChar

### ISSUE THREAD

**Issue by 552020** [dantol29/webserver#110]
Yesterday I tested compilation on Ubuntu on my branch after merging main into it and I got the error reported below. Strangely Leo which did the same test didn't get it, and so Daniil. The function is in HTTPRequestUtils.c<br> <br><br>The function:

```
bool isInvalidChar(const char &c) { 
  if ((c >= 0 && c <= 31) || c == 127) 
  return (true); return (false); } 
```

The error:

```
src/HTTPRequestUtils.cpp: In function ‘bool isInvalidChar(const char&):

src/HTTPRequestUtils.cpp:18:16: error: comparison is always true due to limited range of data type [-Werror=type-limits] 
18 | if ((c >= 0 && c <= 31) || c == 127) 
| ^~ cc1plus: all warnings being treated as errors make: *** [Makefile:31: obj/src/HTTPRequestUtils.o] Error 1
```

The error is saying that basically for unsigned char the `c >= 0` will be always true and the compiler doesn't like it. The problem could be that the system on school is treating char are possibly signed char and my virtual machine not. My fix was to change `const char` to `const unsigned char` and remove the `c >= 0` part. <br><br>This change is only on my branch, but if the PR get accepted will become main, and so I wanted to ask @dtolmaco if this change is bearable.
